language: android

jdk: openjdk7

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.0
    - extra-android-support
    - extra-android-m2repository
    - android-MNC

before_script:
  - chmod +x ./gradlew

script:
  - ./gradlew clean assembleDebug
