language: android

jdk: openjdk7

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.1
    - extra-android-support
    - extra-android-m2repository
    - android-23

before_script:
  - chmod +x ./gradlew

script:
  - ./gradlew clean assembleDebug
